### ISSUE TITLE
Help points to incorrect commands

### ISSUE THREAD

**Issue by cteyton** [jrfaller/diggit#12]
dgit help commands indicates : 

 dgit perform_cli analyses [SOURCE_DEFS*]  # Perform the configured analyses to the sources corresponding to the provided source definitions (id or URL). Analyze all source...
  dgit perform_cli clones [SOURCE_DEFS*]    # Clone the sources corresponding to the provided source definitions (id or URL). Clone all sources if no source definitions are ...
  dgit perform_cli help [COMMAND]           # Describe subcommands or one specific subcommand
  dgit perform_cli joins                    # Perform the configured joins.

Main issue : "perform_cli" does not exist and it should be "perform" instead.
Minor issue : the text is incomplete and should not be cut

**Comment by jrfaller** [comment]
This is fixed in 2.0.0.
