### ISSUE TITLE
Store analysis execution time

### ISSUE THREAD

**Issue by mpalyart** [jrfaller/diggit#18]
In the journal config file for each source store how long each analysis took to execute

**Comment by jrfaller** [comment]
We could also store the starting and ending timestamps, no?

**Comment by mpalyart** [comment]
Yeap good idea to have the starting timestamp. I would still store the execution time instead of the ending timestamp. That way the interesting info would be directly available and if necessary it's always possible to compute the ending timestamp.

**Comment by jrfaller** [comment]
OK this should be done in develop branch, you can try it out.
