### ISSUE TITLE
Unkown Error while installing gem on Windows

### ISSUE THREAD

**Issue by SainathKaluva** [jrfaller/diggit#27]
I Installed Ruby gems for Windows. And tried to execute `gem install diggit`.  Here's the Output in command line. 

    Temporarily enhancing PATH for MSYS/MINGW...
    Building native extensions. This could take a while...
    ERROR:  Error installing diggit:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rugged-0.27.0/ext/rugged
    C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180510-14512-s8tahm.rb extconf.rb
    checking for make... yes
    checking for cmake... no
    ERROR: CMake is required to build Rugged.
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

      C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rugged-0.27.0/mkmf.log

    extconf failed, exit code 1

    Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rugged-0.27.0 for 
    inspection.
    Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rugged- 
    0.27.0/gem_make.out

Thanks in advance for the help.

**Comment by jrfaller** [comment]
I assume you got it working?

**Comment by DoctorChill** [comment]
Yes, it did. After I manually install Cmake for windows. Thanks!
